<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BLT1223" name="testNGdemo.PriorityTestCAse" tests="3" failures="0" timestamp="17 Feb 2020 08:19:49 GMT" time="0.053" errors="1">
  <testcase name="testcase3" time="0.001" classname="testNGdemo.PriorityTestCAse"/>
  <testcase name="testcase1" time="0.002" classname="testNGdemo.PriorityTestCAse"/>
  <testcase name="testcase2" time="0.050" classname="testNGdemo.PriorityTestCAse">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testcase2() didn&#039;t finish within the time-out 5">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testcase2() didn't finish within the time-out 5
]]>
    </error>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- testNGdemo.PriorityTestCAse -->
